{% set version = "1.5.4" %}
{% set sha256 = "57b4b68d81852d4c7350d3788cfeaf6093cb9cdf8dd524fe10ad33581f55e043" %}

package:
  name: cyclus
  version: {{ version }}

source:
  fn: cyclus-{{ version }}-{{ sha256 }}.tar.gz
  url: https://github.com/cyclus/cyclus/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: True  # [win or py<=27]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - cmake
    - pkg-config
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - glibmm
    - glib 2.56
    - jinja2
    - pandas
    - cython < 0.29
    - coincbc <2.9.10
    - boost-cpp <1.69
    - libblas
    - libcblas
    - liblapack
    - libxmlpp
    - bzip2
    - hdf5
    - sqlite
    - pcre
    - gettext
    - xz
  run:
    - python
    - jinja2
    - pandas
    - glibmm
    - glib 2.56
    - libxmlpp
    - {{ pin_compatible("coincbc", max_pin="x.x.x") }}
    - libblas
    - libcblas
    - liblapack
    - {{ pin_compatible("boost-cpp", max_pin="x.x.x") }}
    - hdf5
    - sqlite
    - pcre
    - gettext
    - bzip2
    - xz
    - websockets
    - pprintpp

test:
  requires:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - setuptools
    - nose
    - pytables
  source_files:
    - tests

about:
  home: http://fuelcycle.org/
  license: BSD 3-clause
  license_file: LICENSE.rst
  summary: "The agent-based fuel cycle simulator."

extra:
  recipe-maintainers:
    - scopatz
    - gonuke
    - bam241
    - katyhuff
    - FlanFlanagan
