{% set version = "1.4.0rc1" %}
{% set org = "cyclus" %}
{% set branch = "develop" %}
{% set sha256 = "7a6bd1334f3fd13ddac73fbb7a5218b958b793b81bda26552e9c3abbf255a905" %}
{% set variant = "openblas" %}

package:
  name: cyclus
  version: {{ version }}

source:
  fn: cyclus-{{ version }}-{{ sha256 }}.tar.gz
  url: https://github.com/{{ org }}/cyclus/archive/{{ branch }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  skip: True  # [win or not py35]
  detect_binary_files_with_prefix: true
  features:
    - blas_{{ variant }}

requirements:
  build:
    - toolchain
    - python
    - cmake
    - pkg-config
    - libxmlpp
    - coincbc
    - blas 1.1 {{ variant }}
    - openblas 0.2.18|0.2.18.*
    - boost 1.61.*
    - hdf5 1.8.17|1.8.17.*
    - sqlite 3.13.*
    - pcre
    - gettext
    - bzip2 1.0.*
    - xz 5.2.*
  run:
    - libxmlpp
    - coincbc
    - blas 1.1 {{ variant }}
    - openblas 0.2.18|0.2.18.*
    - boost 1.61.*
    - hdf5 1.8.17|1.8.17.*
    - sqlite 3.13.*
    - pcre
    - gettext
    - bzip2 1.0.*
    - xz 5.2.*

test:
  requires:
    - setuptools
    - nose
    - pytables

about:
  home: http://fuelcycle.org/
  license: BSD 3-clause
  license_file: LICENSE.rst
  summary: "The agent-based fuel cycle simulator."

extra:
  recipe-maintainers:
    - scopatz
