travis:
  secure:
    BINSTAR_TOKEN: UqmgH3yFjLodEHkEo8eHt4sLqmeTBNvjW1kPlnZTg1PT9ESzM0u9a32IG1hSpJrJFiRPVNzySMFOep4iPrxfgOpTgVw1eFP/WcvLw43vuOTEKn/vCnGqEbKt/jurJvbkyMcLkGK7xm/eLoxT1i/2fA2L56+uYPJdMAVFZKsfDmngURjDmEBCpP0xnNNay69gS22aiSiflka+YSgcZMYNUbfnhxotM91oLpwqAzcXHOIwFajV8MTq1sVSTf2fuQPN5qr1KgPCxI0NhP5m6+yEd+5sW/YclhpFKqyF0dAAdhCndhepzw+386ZuwrCTezdwlvZ4HMRvWqr2hRoxcvCu6isKO5ZRodyPJ3gRB0Tnnx9mKqTAIboi2p+oybDYgRCViYx/pT/8NqqTxauks1HQ+U33rLqPMtXs2p6Kg1ZSvvi+UrLSTYpjLAQNX2yMqK9xDzxI6EMaFsv3tR9n3F2DzinRy0+Ahp7MEMgMkuT1C59+9NwHVsLpugFTnDayUdTsAEIIVHx9px2a/UNloLDyKzZZ1cB1+P2BQ1iP09b4ijFt1UB8W/Ax5trSfi/LXuUtSEFlOMMRAgtrjolA8oMgjlF653/vLmOqquNYTugzOJpOBUjA2ijMMmOV0uqYg48+9WBXQ1Sw4qY+hngR16RO030uswEvC8l22bNFJdC1XZI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
