travis:
  secure:
    BINSTAR_TOKEN: QlO4bydE9Xfs8X5DuNYAFR8yCmwFiaWg9xy74VxCiDvZHaBQJRNIDI5KrygdCsv00eKNjemv6ipzpfJI4uxq9A9lqXYXigZT/pyDrhCcPAf0KL9uW5tCBx0Y23E3FQBhiiZX2DqVyM32xj43dBU9wb7wQt2VvkPTfmvD66RoosvXsLFu/wuXLbnDBURTi7Lc82v6mhcWkPVlJMWFG7NB9DEqFCr7aYaV1Ko8yuo/KODB3BY8Vau5eFi7S3xzYrEFsbk9KSdFBHuI9TMR7N0+UpowtYbKInrfDUOFwXQiCo8pg7Nw0o5spbU+0KtaiKlrfHVSKY8HWfKPnRCcdo3wW+qthaVFPjQr0kCx9OvaeXKVoogqS2qlq2G3xsnVpxoF8UPexeUSDdLJ8qiA5vSbRoIuVy06FIN50D0IJuHYimTSUD5luv7xIvRz+mBh729BHHegvuL4HRFi0v4sFfE5QnKPFUo/g+q/a41U2hM3ob+w1bY9SnhbHbEIIeHSeGz2aVbyxNB5+xAmAHuKadOu5BXC4JfKh7sKGjuCFhlukp3ui9zwN9+wuJCIQ35MtztS2NGJudYm1oNHDvkdov9bSWhrOTdDBUSHdzs0bN+dxqEj+ZBqx/dOZXe7AAwAr0KfxSLv5xVCzbKLE1373on7B+K8Z3taPZBumiufg38s8BU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
